import { Entities } from "../userEntities";
import { Tweet } from "./Tweet";

export type User = {
  contributors_enabled: boolean;
  created_at: string;
  default_profile: boolean;
  default_profile_image: boolean;
  description?: string;
  entities: Entities;
  favourites_count: number;
  followers_count: number;
  following: boolean;
  follow_request_sent: boolean | null;
  friends_count: number;
  geo_enabled: boolean;
  has_extended_profile: boolean;
  id: number;
  id_str: string;
  is_translation_enabled: boolean;
  is_translator: boolean;
  lang: string;
  listed_count: number;
  location: string;
  name: string;
  needs_phone_verification: boolean;
  notifications: boolean;
  profile_background_color: string | null;
  profile_background_image_url: string | null;
  profile_background_image_url_https: string | null;
  profile_background_tile: string | null;
  profile_banner_url: string;
  profile_image_url: string;
  profile_image_url_https: string;
  profile_link_color: string | null;
  profile_location: null;
  profile_sidebar_border_color: null;
  profile_sidebar_fill_color: null;
  profile_text_color: null;
  profile_use_background_image: null;
  protected: boolean;
  screen_name: string;
  status: Tweet;
  statuses_count: number;
  suspended: boolean;
  time_zone: string;
  translator_type: string;
  url: string;
  utc_offset: boolean;
  verified: boolean;
};
